[project]
name = "tristan-havelick-website"
version = "0.1.0"
description = "Tristan's personal website"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "flask>=3.1.0",
    "html-to-markdown>=1.2.0",
    "lxml>=5.3.1",
]

