version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Site
          command: npm run build
      - when:
          condition:
            equal: [ circle, << pipeline.git.branch >> ]
          steps:
            - run: gatsby deploy